- name: Issue Bot Action
  uses: imjohnbo/issue-bot@v3.3.4



name: Submission Reminder
on:
  schedule:
    - cron: 10 13 3 12 *

jobs:
  create_issue:
    name: Reminder
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Reminder
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          assignees: "FrustT, EgeOnder"
          labels: ""
          title: "Reminder"
          body: |
          Submit Your .py file
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
